In [4]:
"""
 author:jjk
 datetime:2019/12/01
 coding:utf-8
 project name:Pycharm_workstation
 Program function: 处理数据缺失值

"""

import numpy as np
from numpy import *

In [23]:
# 加载数据集
def loadDataSet(filename,delim='\t'):
    fr = open(filename)
    stringArr = [line.strip().split(delim) for line in fr.readlines()]
    #print(stringArr) # 就是一个二维数组
    datArr = [list(map(float,line)) for line in stringArr]
    # print('\n')
    # print(datArr)
    return mat(datArr)

In [28]:
'''将NaN替换成平均值函数'''
def replaceNanWithMean():
    datMat = loadDataSet('../dataSet/files/dataset.data','    ') # 获取数据集
    numFeat = shape(datMat) # numpy中的一个方法
    # print(numFeat[1]-1)  # 特征数3
    for i in range(numFeat[1]-1):
        # 对value不为NaN的求均值，A 返回矩阵基于的数组
        # print(datMat[nonzero(~isnan(datMat[:, i].A))[0],i]) # 列特征非nan数据
        # datArr[:,i].A)：获取datArr的列，每一列进行一个矩阵的转换；(~isnan())[0]:如果每一列的数据不是nan里面所有的值
        # nonzero(,i):不为零的一个方法；mean():numpy中的均值
        meanVal = mean(datMat[nonzero(~isnan(datMat[:, i].A))[0], i]) # 获取均值
        # 将value为NaN的值赋值为均值
        datMat[nonzero(isnan(datMat[:, i].A))[0],i] = meanVal # 将均值赋到其中
    return datMat


In [29]:
# 主函数
if __name__ == '__main__':
    # 加载数据集
    loadDataSet(r'../dataSet/files/dataset.data','   ')
    # print(datArr)
    
    # 均值填补缺失值
    datMat = replaceNanWithMean()# 加载这个数据
    print(datMat)


[[3.33022113e+04 8.32697600e+00 9.53952000e-01 3.00000000e+00]
 [1.44880000e+04 7.15346900e+00 1.67390400e+00 2.00000000e+00]
 [2.60520000e+04 6.56491342e+00 8.05124000e-01 1.00000000e+00]
 [7.51360000e+04 1.31473940e+01 4.28964000e-01 1.00000000e+00]
 [3.83440000e+04 1.66978800e+00 1.34296000e-01 1.00000000e+00]
 [7.29930000e+04 6.56491342e+00 1.03295500e+00 1.00000000e+00]
 [3.59480000e+04 6.83079200e+00 1.21319200e+00 3.00000000e+00]
 [4.26660000e+04 1.32763690e+01 8.22827255e-01 3.00000000e+00]
 [6.74970000e+04 6.56491342e+00 8.22827255e-01 1.00000000e+00]
 [3.54830000e+04 1.22731690e+01 1.50805300e+00 3.00000000e+00]
 [5.02420000e+04 3.72349800e+00 8.31917000e-01 1.00000000e+00]
 [6.32750000e+04 8.38587900e+00 1.66948500e+00 1.00000000e+00]
 [5.56900000e+03 4.87543500e+00 7.28658000e-01 2.00000000e+00]
 [6.80800000e+03 1.36483800e+00 6.40103000e-01 2.00000000e+00]
 [4.16110000e+04 2.30453000e-01 1.15199600e+00 1.00000000e+00]
 [3.66610000e+04 1.18654020e+01 8.82810000e-01 3.000000