In [2]:
"""
 author:jjk
 datetime:2019/12/01
 coding:utf-8
 project name:Pycharm_workstation
 Program function:   解析数据文件，返回特征集和标签
 
"""

'''
特征数据集：
特征1：年均投入时间（min）
特征2：玩游戏占时间百分比
特征3：每天看综艺的时间（h）
标签集：
1：学习专注
2：学习正常
3：比较贪玩
'''
import os
from numpy import *

In [5]:
def file_matrix(filepath):
    file = open(filepath,'r',encoding='utf-8')
    arrayLines = file.readlines()
    # print(arrayLines)
    returnMat = zeros((len(arrayLines),3)) # len(arraylines)行，3列——特征数据集
    # print(returnMat)
    
    classLabelMat = [] # 标签集
    index = 0 # 索引
    for line in arrayLines: 
        listForLine = line.strip().split('\t')
        returnMat[index,:] = listForLine[0:3] # 获取前散列
        classLabelMat.append(int(listForLine[-1])) # 添加最后一个字段
        index += 1
    file.close()
    return returnMat,classLabelMat # 返回：特征矩阵，标签矩阵
    

In [6]:
if __name__ == '__main__':
    filepath = os.path.abspath(r'../dataSet/files/dataset.txt')
    returnMat,classLabelMat = file_matrix(filepath) # 函数实例化
    print('数据集:\n',returnMat,'\n标签集：\n',classLabelMat)
    
    
    

数据集:
 [[4.0920000e+04 8.3269760e+00 9.5395200e-01]
 [1.4488000e+04 7.1534690e+00 1.6739040e+00]
 [2.6052000e+04 1.4418710e+00 8.0512400e-01]
 [7.5136000e+04 1.3147394e+01 4.2896400e-01]
 [3.8344000e+04 1.6697880e+00 1.3429600e-01]
 [7.2993000e+04 1.0141740e+01 1.0329550e+00]
 [3.5948000e+04 6.8307920e+00 1.2131920e+00]
 [4.2666000e+04 1.3276369e+01 5.4388000e-01]
 [6.7497000e+04 8.6315770e+00 7.4927800e-01]
 [3.5483000e+04 1.2273169e+01 1.5080530e+00]
 [5.0242000e+04 3.7234980e+00 8.3191700e-01]
 [6.3275000e+04 8.3858790e+00 1.6694850e+00]
 [5.5690000e+03 4.8754350e+00 7.2865800e-01]
 [6.8080000e+03 1.3648380e+00 6.4010300e-01]
 [4.1611000e+04 2.3045300e-01 1.1519960e+00]
 [3.6661000e+04 1.1865402e+01 8.8281000e-01]
 [4.3605000e+04 1.2046000e-01 1.3520130e+00]
 [1.5360000e+04 8.5452040e+00 1.3404290e+00]
 [6.3796000e+04 5.8566490e+00 1.6000600e-01]
 [1.0743000e+04 9.6656180e+00 7.7862600e-01]
 [7.0808000e+04 9.7787630e+00 1.0841030e+00]
 [7.2011000e+04 4.9329760e+00 6.3202600e-01]
 [5.